# Generated by Django 6.0.1 on 2026-01-07 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Исполнитель')),
                ('tm_id', models.CharField(max_length=50, unique=True, verbose_name='ID Ticketmaster')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название события')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('venue_name', models.CharField(max_length=255, verbose_name='Площадка')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('ticket_url', models.URLField(verbose_name='Ссылка на билеты')),
                ('tm_event_id', models.CharField(max_length=50, unique=True, verbose_name='ID События TM')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.artist')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город поиска')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='events.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
